### ISSUE TITLE
Summary of Dynamics

### ISSUE THREAD

**Issue by rodsonchue** [VengeanceRising/VengeanceRising#24]
These are the Key Dynamics that we target to implement, please also mention if any has been missed out!
1. Object interactions using Leap Motion Controller
   - [ ] #5 Grabbing objects
   - [ ] #11 Storing objects in Inventory
   - [ ] #23 Opening Pepper Caster to uncover clues
   - [ ] #17, #14 Advanced method of travelling around the mansion
2. Menu Mechanics
   - [ ] #12 Object/Clue combination
3. Social
   - [ ] #16 Interacting with other characters (NPCs)
